# Credentials configuration for Agent Auto Load
# This file is stored in a separate repository for security

# OpenAI API credentials
[openai]
api_key = ""  # Your OpenAI API key

# Database credentials
[database]
username = ""
password = ""
host = ""
port = ""
database = ""

# External service credentials
[services]
weather_api_key = ""
mapbox_token = ""

# Environment settings
[environment]
mode = "development"  # Options: development, staging, production
